version: '2'

services:
  proxy:
    build: .
    command: bash -c "ls -a && make all && ./proxy_server"
    volumes:
      - ./src:/src
      - ./logs:/var/logs/erss/
    ports:
      - "12345:12345"
    tty: true
