version: '2'

services:
  proxy:
    build: .
    command: bash -c "ls -a && g++ -o proxy_server proxy_server.cpp -lPocoNet -lPocoUtil -lPocoFoundation -std=c++11 && ./proxy_server"
    volumes:
      - ./src:/src
    ports:
      - "8080:8080"
    tty: true
