version: '3.3'

services:
  proxy:
    build: .
    command: bash -c "ls -a && make all && ./proxy_server"
    volumes:
      - "./src:/src"
      - type: bind
        source: ./logs
        target: /var/logs/erss
    ports:
      - "12345:12345"
    tty: true
