# config.make generated by configure script
POCO_CONFIG = Darwin
POCO_BASE = /Users/farissbahi/Documents/GitHub/CachingProxy/config/poco-1.8.1
POCO_BUILD = /Users/farissbahi/Documents/GitHub/CachingProxy/config/poco-1.8.1
POCO_FLAGS = 
POCO_PREFIX = /usr/local
OMIT = Data/ODBC Data/MySQL MongoDB PDF CppParser
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_FLAGS
export POCO_PREFIX
